from tkinter import*
screen=Tk()
screen.geometry("680x600")
screen.title("weight convert🌡")
screen.config(background="MediumPurple1")
def convert_pound():
    lbs=float(put.get())
    real=str((lbs) *0.453592 )
    aswer.config(text=real)
title=Label(screen,text="pounds to kilos converter",bg="CadetBlue1",fg="MediumPurple1",font=("Lola",15,"bold"))
title.grid(row=1,column=1,padx=140,pady=50)
enter=Label(screen,text="enter the weight in pounds you want to convert",bg="CadetBlue1",fg="MediumPurple1",font=("Lola",15,"bold"))
enter.grid(row=2,column=1,padx=0,pady=50)
put=Entry(screen)
put.grid(row=2,column=2,padx=0,pady=50)
submit=Button(screen,text="Submit",bg="CadetBlue1",fg="MediumPurple1",font=("Lola",15,"bold"),command=convert_pound)
submit.grid(row=3,column=1,padx=90,pady=50)
aswer=Label(screen,bg="MediumPurple1",fg="CadetBlue1",font=("Lola",15,"bold"))
aswer.grid(row=4,column=1,padx=100,pady=50)
screen.mainloop()